version: '3.4'
services:
  mongodb:
      container_name: mongodb
      image: mongo:latest
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - wfdf:/data/db
  scheduler:
    image: jtbry/ofelia:latest
    container_name: scheduler
    depends_on:
      - mongodb
    command: daemon --config=/etc/ofelia/config.ini
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ofelia.ini:/etc/ofelia/config.ini
volumes:
  wfdf:
    external: false