version: '3.4'
services:
  redis:
      container_name: redis
      image: redis:latest
      ports:
        - "6379:6379"
      volumes:
        - wfdf:/data/redis
  mongodb:
      container_name: mongodb
      image: mongo:latest
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - wfdf:/data/db
  scheduler:
    image: jtbry/ofelia:latest
    container_name: scheduler
    depends_on:
      - mongodb
    command: daemon --config=/etc/ofelia/config.ini
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ofelia.ini:/etc/ofelia/config.ini
  api:
    container_name: web-api
    image: web-api
    depends_on:
      - mongodb
    build:
      context: ./src/
      dockerfile: ./Wfdf.Api/Dockerfile
    environment:
      - ConnectionStrings__MongoDb=mongodb://mongodb:27017/
      - ConnectionStrings__Redis=redis:6379
      - ReactAppDomain=http://localhost
    ports:
      - "8080:8080"
  client:
    container_name: client
    image: client
    depends_on:
      - api
    build:
      context: ./src/client
      dockerfile: Dockerfile
      args:
        - API_URL=http://localhost:8080
    ports:
      - "80:80"
volumes:
  wfdf:
    external: false