version: '3.4'
services:
  mongodb:
      container_name: mongodb
      image: mongo:latest
      restart: always
      ports:
        - "27017:27017"
      volumes:
        - wfdf:/data/db
  scheduler:
    image: jtbry/ofelia:latest
    container_name: scheduler
    depends_on:
      - mongodb
    command: daemon --config=/etc/ofelia/config.ini
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./ofelia.ini:/etc/ofelia/config.ini
  api:
    container_name: web-api
    image: web-api
    depends_on:
      - mongodb
    build:
      context: .
      dockerfile: ./src/Wfdf.Api/Dockerfile
    environment:
      - ConnectionStrings__MongoDb=mongodb://mongodb:27017/
      - ReactAppDomain=localhost
    ports:
      - "5207:5207"

volumes:
  wfdf:
    external: false