services:
  items-db:
    container_name: item-db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - wfdf:/data/db
  item-updaters:
    container_name: item-updaters
    build: ./item-updaters/
    image: wfdf:item-updaters
    depends_on:
      - items-db
    environment:
      - mongoConnectionUrl=mongodb://items-db:27017
  item-api:
    container_name: item-api
    build: ./api/
    image: wfdf:item-api
    restart: always
    depends_on:
      - items-db
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - mongoConnectionUrl=mongodb://items-db:27017
    volumes: 
      - ./api:/usr/src/app
    command: "npm run dev"
  wfdf-client:
    container_name: wfdf-client
    build:
      context: ./client/
      dockerfile: Dockerfile.dev
    image: wfdf:client
    restart: always
    ports:
      - "80:3000"
    volumes:
      - ./client:/usr/src/app
    environment: 
      - CHOKIDAR_USEPOLLING=true
volumes:
  wfdf:
    external: false
